server:
  port: 81

eureka:
  client:
    register-with-eureka: false  #表示是否将自己注册进eurekaServer，默认为true
    fetch-registry: true        #是否从eurekaServer中抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true
    service-url:
      defaultZone: http://localhost:7001/eureka/
      #defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka #集群版

feign:
  hystrix:
    enabled: true


logging:
  level:
    #feign日志以什么级别监控那个接口
    com.atguigu.springclud.service.PaymentFeignService: debug
